export const projects = [
  {
    id: 1,
    name: "Project 1",
    description: "Description of Project 1",
    status: "In Progress",
    memberIds: [1, 3, 6],
  },
  {
    id: 2,
    name: "Project 2",
    description: "Description of Project 2",
    status: "Completed",
    memberIds: [2, 4, 5],
  },
  {
    id: 3,
    name: "Project 3",
    description: "Description of Project 3",
    status: "Not Started",
    memberIds: [1, 2],
  },
  {
    id: 4,
    name: "Project 4",
    description: "Description of Project 4",
    status: "In Progress",
    memberIds: [3, 5, 6],
  },
  {
    id: 5,
    name: "Project 5",
    description: "Description of Project 5",
    status: "Completed",
    memberIds: [1, 4],
  },
  {
    id: 6,
    name: "Project 6",
    description: "Description of Project 6",
    status: "Not Started",
    memberIds: [2, 3, 6],
  },
  {
    id: 7,
    name: "Project 7",
    description: "Description of Project 7",
    status: "In Progress",
    memberIds: [1, 5],
  },
  {
    id: 8,
    name: "Project 8",
    description: "Description of Project 8",
    status: "Completed",
    memberIds: [2, 4, 6],
  },
  {
    id: 9,
    name: "Project 9",
    description: "Description of Project 9",
    status: "Not Started",
    memberIds: [3, 5],
  },
  {
    id: 10,
    name: "Project 10",
    description: "Description of Project 10",
    status: "In Progress",
    memberIds: [1, 2, 4],
  },
];
