export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@email.com",
    phone: "1234567890",
    profile: "https://randomuser.me/api/portraits/men/60.jpg",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@email.com",
    phone: "0987654321",
    profile: "https://randomuser.me/api/portraits/women/49.jpg",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@email.com",
    phone: "1122334455",
    profile: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob.brown@email.com",
    phone: "2233445566",
    profile: "https://randomuser.me/api/portraits/men/70.jpg",
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie.davis@email.com",
    phone: "3344556677",
    profile: "https://randomuser.me/api/portraits/men/69.jpg",
  },
  {
    id: 6,
    name: "Diana Prince",
    email: "diana.prince@email.com",
    phone: "4455667788",
    profile: "https://randomuser.me/api/portraits/women/50.jpg",
  },
  {
    id: 7,
    name: "Ethan Hunt",
    email: "ethan.hunt@email.com",
    phone: "5566778899",
    profile: "https://randomuser.me/api/portraits/men/71.jpg",
  },
  {
    id: 8,
    name: "Fiona Gallagher",
    email: "fiona.gallagher@email.com",
    phone: "6677889900",
    profile: "https://randomuser.me/api/portraits/women/51.jpg",
  },
  {
    id: 9,
    name: "George Clooney",
    email: "george.clooney@email.com",
    phone: "7788990011",
    profile: "https://randomuser.me/api/portraits/men/72.jpg",
  },
  {
    id: 10,
    name: "Hannah Montana",
    email: "hannah.montana@email.com",
    phone: "8899001122",
    profile: "https://randomuser.me/api/portraits/women/52.jpg",
  },
];
